# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    - /Volumes/Macintosh HD2/Users2/tmp/2018-07-20/host:/opt/tmp